-- Run this in your Supabase SQL Editor
-- Creates the friendships table for the friend request system

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  friend_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  -- Prevent duplicate friend requests in either direction
  unique (user_id, friend_id)
);

alter table public.friendships enable row level security;

create index if not exists friendships_user_id_idx on public.friendships (user_id);
create index if not exists friendships_friend_id_idx on public.friendships (friend_id);
create index if not exists friendships_status_idx on public.friendships (status);
