CREATE TABLE IF NOT EXISTS public.games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  genre text NOT NULL,
  stage text,
  status text NOT NULL DEFAULT 'Live',
  href text,
  image text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;

-- Allow read access for everyone
CREATE POLICY "Enable read access for all users" ON public.games
  FOR SELECT USING (true);

-- Insert seed data
INSERT INTO public.games (title, genre, stage, status, href, image) VALUES
  ('Sky Hopper', 'Arcade', 'Flappy-style', 'Live', '/flappy', '/images/sky_hopper_1789299722470.png'),
  ('Neon Match', 'Puzzle', 'Memory', 'Live', '/memory', '/images/neon_match_1789299759422.png'),
  ('Pulse Reflex', 'Speed', 'Reaction', 'Live', '/reaction', '/images/pulse_reflex_1789299783039.png'),
  ('Lucky Dice', 'Chance', 'Dice duel', 'Live', '/dice', '/images/lucky_dice_1789299795505.png'),
  ('Neon Snake', 'Arcade', 'Grid chase', 'Live', '/snake', '/images/neon_snake_1789299734826.png'),
  ('Pong Arena', 'Arcade', '2-player duel', 'Live', '/pong', '/images/pong_arena_1789299746830.png'),
  ('Aim Blaster', 'Action', 'Target rush', 'Live', '/aimblaster', '/images/aim_blaster.png'),
  ('Number Crush', 'Puzzle', 'Speed order', 'Live', '/numbercrush', '/images/number_crush.png'),
  ('Color Storm', 'Memory', 'Pattern recall', 'Live', '/colorstorm', '/images/color_storm.png'),
  ('Brick Blaster', 'Arcade', 'Break em all', 'New', '/brickblaster', '/images/brick_blaster.png'),
  ('Word Blitz', 'Speed', 'Typing rush', 'New', '/wordblitz', '/images/word_blitz.png');
