-- Create the device table for the frontend device manager.
create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  manufacturer text not null default '',
  model text not null default '',
  serial_number text not null default '' unique,
  location text not null default '',
  image_url text not null default '',
  status text not null default 'Online' check (status in ('Online', 'Offline')),
  last_seen timestamptz not null default now(),
  specifications jsonb not null default '{}'::jsonb,
  notes text not null default '',
  created_at timestamptz not null default now()
);

alter table public.devices enable row level security;

create index if not exists devices_status_idx on public.devices (status);
create index if not exists devices_location_idx on public.devices (location);
