create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text not null,
  phone text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  progress_data jsonb not null default '[]'::jsonb,
  avatar_url text not null default '',
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

alter table public.users add column if not exists progress_data jsonb not null default '[]'::jsonb;
alter table public.users add column if not exists avatar_url text not null default '';

create index users_email_lower_idx on public.users (lower(email));

create table public.devices (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  manufacturer text not null default '',
  model text not null default '',
  serial_number text not null default '' unique,
  location text not null default '',
  image_url text not null default '',
  status text not null default 'Online' check (status in ('Online', 'Offline')),
  last_seen timestamptz not null default now(),
  specifications jsonb not null default '{}'::jsonb,
  notes text not null default '',
  created_at timestamptz not null default now()
);

alter table public.devices enable row level security;

create index devices_status_idx on public.devices (status);
create index devices_location_idx on public.devices (location);

insert into public.devices (name, type, manufacturer, model, serial_number, location, image_url, status, specifications, notes)
values
  ('Reception tablet', 'Tablet', 'Apple', 'iPad Air', 'TAB-REC-001', 'Front desk', 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=160&q=80', 'Online', '{"RAM":"8GB","Battery":"10h","OS":"iPadOS 18"}', 'Visitor check-in device'),
  ('Warehouse scanner', 'Scanner', 'Zebra', 'DS2208', 'SCN-WH-014', 'Warehouse A', 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=160&q=80', 'Online', '{"Scan":"1D / 2D","Connection":"Bluetooth","Battery":"14h"}', 'Assigned to warehouse team'),
  ('Meeting room display', 'Display', 'Samsung', 'QB43R', 'DSP-R02-008', 'Room 02', 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=160&q=80', 'Offline', '{"Size":"43 inch","Resolution":"4K UHD","OS":"Tizen"}', 'Check power connection')
on conflict do nothing;

create table public.game_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  game_name text not null,
  score integer not null default 0,
  played_at timestamptz not null default now()
);

alter table public.game_logs enable row level security;
create index game_logs_user_id_idx on public.game_logs (user_id);

create table public.achievements (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  unlocked_at timestamptz not null default now()
);

alter table public.achievements enable row level security;
create index achievements_user_id_idx on public.achievements (user_id);